name: CI
on:
  workflow_dispatch:
    inputs:
      level:
        description: Logging Level
        required: true
        default: INFO
        type: choice
        options:
          - CRITICAL
          - FATAL
          - ERROR
          - WARNING
          - WARN
          - INFO
          - DEBUG
          - NOTSET
      pool:
        description: Number of threads
        required: true
        default: 8
      retry:
        description: Number of retries
        required: true
        default: 3
      time:
        description: Update wait time
        required: true
        default: 1
      limit:
        description: limit
        required: false
      update-config:
        description: update-config
        default: false
        type: boolean
      ini-config:
        description: ini-config
        default: false
        type: boolean
      get-dlc:
        description: get-dlc
        default: false
        type: boolean
      args:
        description: args
        required: false
    branches:
      - main
  schedule:
    - cron: '0 3 * * *'
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          repository: lls7890/MyManifestAutoUpdate
          token: ${{ secrets.TOKEN_FOR_OTHER_REPO }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 配置Git
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: 运行主脚本
        shell: bash
        run: |
          LEVEL="${{ github.event.inputs.level }}"
          POOL="${{ github.event.inputs.pool }}"
          RETRY="${{ github.event.inputs.retry }}"
          TIME="${{ github.event.inputs.time }}"
          LIMIT="${{ github.event.inputs.limit }}"
          UPDATE_CONFIG="${{ github.event.inputs.update-config }}"
          INI_CONFIG="${{ github.event.inputs.ini-config }}"
          GET_DLC="${{ github.event.inputs.get-dlc }}"
          ARGS="${{ github.event.inputs.args }}"
          COMMAND="python main.py -l ${LEVEL} -p ${POOL} -r ${RETRY} -t ${TIME} -k ${{ secrets.KEY }} ${ARGS}"
          if [ -n "$LIMIT" ]; then
            COMMAND="${COMMAND} -limit ${LIMIT}"
          fi
          if [ -n "$UPDATE_CONFIG" = "true" ]; then
            COMMAND="${COMMAND} -update-config"
          fi
          if [ -n "$INI_CONFIG" = "true" ]; then
            COMMAND="${COMMAND} -ini-config"
          fi
          if [ -n "$GET_DLC" = "true" ]; then
            COMMAND="${COMMAND} -get-dlc"
          fi
          echo "运行命令: $COMMAND"
          $COMMAND